### ISSUE TITLE
US 01.01.01: As a doer, I want to add a habit, giving it a brief title, reason, and date to start

### ISSUE THREAD

**Issue by cefong** [CMPUT301F21T41/Habbit#2]
Story Points: 2

- [ ] Create Habit class / objects
- [ ] Create User class / objects
- [ ] Integrate Add function with Firestore

- [ ] create "adding habit" fragment

**Comment by joRusk** [comment]
Story Points: 2

**Comment by joRusk** [comment]
-> Create Habit class / objects
-> Create User class / objects
-> outline how Habits will be integrated with Firestore
-> create main (viewing user habits) screen
-> create "adding habit" fragment
