### ISSUE TITLE
Create a draft list of proposed 'screens' to be included

### ISSUE THREAD

**Issue by joRusk** [CMPUT301F21T41/Habbit#26]
- [x] Profile Screen View
- [x] Social Feed View (include button to add friends)
- [x] Add friend overlay (by searching, or add directly by username, up to you!)
- [x] Friend request overlay (as popup notification)
- [x] Habit Event List View
- [x] Edit habit event overlay
- [x] View habit event details overlay
- [x] Login screen
- [x] User registration screen

**Comment by cefong** [comment]
When labelling the UI mockup, we should include the following:
- A transition arrow for each interaction the user can have on the screen
- Labels under each screen for what user stories it covers (if any)
