### ISSUE TITLE
Update UI Mockups/Storyboard Sequences

### ISSUE THREAD

**Issue by cefong** [CMPUT301F21T41/Habbit#55]

**Comment by jteengfo** [comment]
**Updated US** 

- [ ] US 01.01.01 - add public/private switch button
- [ ] US 01.05.01 - create a confirmation window if delete
- [ ] US 05.01.01 - ask another doer to follow all public habits (Jill says the current setup is good as is)
- [ ] US 05.02.01 - grant deny doer permission to follow 
- [ ] US 05.03.01 - view habits and visual indicators of other doers granted to follow
- [ ] US 06.01.01 - habit event to have optional location to record where it happened

**New US**

- [ ] US 01.08.02 - as a doer, i want to manually reorder habits on my list of habits.
- [ ] US 02.03.02 - as a doer, i want the photograph for a habit event to be taken with the camera within the app
- [ ] US 06.01.02 - as a doer, i want to location for a habit event to be specified using a map within the app, with the current phone position as the default location.

**Comment by jteengfo** [comment]
**Jill's email**

- [ ] Once a picture or location is selected for a habit event, is there any way for the user to see details or any visual confirmation _before_ saving that a photo or location has been selected?
- [ ] Will there be a warning/confirmation if a user is about to delete a habit or event?
- [ ] Consider Tuesday and Thursday should be differentiated in the habit add/edit fragment

**Comment by jteengfo** [comment]
- [ ] Add arrow (on submit click) from last add image overlay
- [ ] Add visual indicators for both location and photo being added
