### ISSUE TITLE
Fix UI before demo :)

### ISSUE THREAD

**Issue by cefong** [CMPUT301F21T41/Habbit#78]
- [x] Fix Action Bar to reflect Figma more (so make background of actionbar same color as background of the app), add logo to left side if possible, and don't worry about dropdown menu yet
- [x] Fix List items to be cards instead of boring
- [x] Fix Habit Details Fragment (find a way to make habit title the title of the fragment)

**Comment by jteengfo** [comment]
Hello! 

I have added text styles in themes.xml (Thanks to Celine for that tip!) and applied them to various textviews in:

- fragment_habit_details.xml
- fragment_habit_event_details.xml
- list_content.xml
- habit_event_list_content.xml

![image](https://user-images.githubusercontent.com/57475615/142138517-3c8ec8c4-77f5-457f-8e0c-693f4d70409f.png)
![image](https://user-images.githubusercontent.com/57475615/142138555-96d9bced-ebea-441b-a00e-c2949ae1aabe.png)
![image](https://user-images.githubusercontent.com/57475615/142138580-d3b4c1b1-f57a-451e-80d0-78ef81c71a81.png)
![image](https://user-images.githubusercontent.com/57475615/142138603-41d3638b-c414-4a11-a130-7acc68fb6804.png)
