### ISSUE TITLE
US 01.07.01: As a doer, I want to see what habits I need to do today

### ISSUE THREAD

**Issue by joRusk** [CMPUT301F21T41/Habbit#9]
Story Points: 2
### Relevant Intent Tests
- [ ] Test Day List View (add, edit, delete etc.)

### Relevant Unit Tests
- [ ] add habit
- [ ] edit habit
- [ ] delete habit

**Comment by joRusk** [comment]
Story Points: 2

**Comment by cefong** [comment]
### Relevant Intent Tests
- [ ] Test Day List View (add, edit, delete etc.)

### Relevant Unit Tests
- [ ] add habit
- [ ] edit habit
- [ ] delete habit
